import './style.css';
import { formatProductSummary, products } from './products';

const clock = document.querySelector<HTMLTimeElement>('#factory-clock');
const buildTime = document.querySelector<HTMLTimeElement>('#build-time');
const summary = document.querySelector<HTMLElement>('#product-summary');
const utcClock = new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false, timeZone: 'UTC' });
const buildFormatter = new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', timeZone: 'UTC', timeZoneName: 'short' });

function updateClock(): void {
  if (!clock) return;
  const now = new Date();
  clock.dateTime = now.toISOString();
  clock.textContent = utcClock.format(now);
}

if (buildTime) {
  const builtAt = new Date(__BUILD_TIMESTAMP__);
  buildTime.dateTime = builtAt.toISOString();
  buildTime.textContent = buildFormatter.format(builtAt);
}
if (summary) summary.textContent = formatProductSummary(products);
void renderLedger();
updateClock();
window.setInterval(updateClock, 1000);


/* ---- Release ledger: the live catalog, generated by the factory into /products.json ---- */
type Entry = { slug: string; title: string; url: string; class: string; territory: string; description: string; paid: boolean; state: string };
const KIND: Record<string, string> = { 'static-web': 'web', 'pwa-offline': 'offline app', 'web-with-backend': 'web + backend', 'library-npm': 'npm library', 'library-pypi': 'python library', 'library-crate': 'rust crate', cli: 'cli', 'browser-extension': 'browser extension', android: 'android', 'desktop-app': 'desktop app', 'cli-installers': 'cli installers', 'android-apk': 'android apk', 'ios-ipa': 'ios (sideload)' };
function esc(s: string): string { return s.replace(/[&<>"]/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[ch] ?? ch); }

async function renderLedger(): Promise<void> {
  const grid = document.querySelector<HTMLOListElement>('#ledger-grid');
  const filters = document.querySelector<HTMLElement>('#ledger-filters');
  const search = document.querySelector<HTMLInputElement>('#ledger-search');
  const count = document.querySelector<HTMLElement>('#ledger-count');
  if (!grid || !filters || !search || !count) return;
  let entries: Entry[] = [];
  try {
    const res = await fetch('/products.json', { cache: 'no-cache' });
    if (res.ok) entries = ((await res.json()) as { products?: Entry[] }).products ?? [];
  } catch { /* the ledger degrades to the empty state below */ }
  if (entries.length === 0) { grid.innerHTML = '<li class="ledger-empty">The ledger is being sealed. Check back in a few minutes.</li>'; return; }
  if (summary) summary.textContent = `${entries.length} tools live on their own addresses.`;
  const kinds = new Map<string, number>();
  for (const e of entries) kinds.set(e.class, (kinds.get(e.class) ?? 0) + 1);
  let kind: string | null = null;
  filters.innerHTML = [...kinds.entries()].sort((a, b) => b[1] - a[1]).map(([k, n]) => `<button type="button" data-kind="${esc(k)}" aria-pressed="false">${esc(KIND[k] ?? k)} · ${n}</button>`).join('');
  grid.innerHTML = entries.map((e) => `<li data-kind="${esc(e.class)}" data-search="${esc((e.title + ' ' + e.description + ' ' + e.slug + ' ' + e.territory).toLowerCase())}">
    <div class="ledger-meta"><span>${esc(KIND[e.class] ?? e.class)}</span>${e.paid ? '<span class="paid">paid tier</span>' : ''}${e.state === 'VERIFYING' ? '<span class="fresh">just shipped</span>' : ''}</div>
    <h3><a href="${esc(e.url)}">${esc(e.title)}</a></h3>
    <p>${esc(e.description || 'Live and ready to try.')}</p>
    <span class="address">${esc(e.url.replace('https://', ''))}</span>
  </li>`).join('');
  const items = [...grid.querySelectorAll<HTMLLIElement>('li')];
  const apply = (): void => {
    const q = search.value.trim().toLowerCase();
    let shown = 0;
    for (const li of items) { const ok = (!q || (li.dataset.search ?? '').includes(q)) && (!kind || li.dataset.kind === kind); li.hidden = !ok; if (ok) shown++; }
    count.textContent = shown === entries.length ? `${entries.length} tools` : `${shown} of ${entries.length} tools`;
    filters.querySelectorAll<HTMLButtonElement>('button').forEach((b) => b.setAttribute('aria-pressed', String(b.dataset.kind === kind)));
  };
  search.addEventListener('input', apply);
  filters.addEventListener('click', (ev) => { const b = (ev.target as HTMLElement).closest('button'); if (!b) return; kind = kind === b.dataset.kind ? null : (b.dataset.kind ?? null); apply(); });
  apply();
}
